version: '3.8'
services:
  jenkins:
    image: delinel/devops:myjenkins-1.0.0
    restart: always
    container_name: jenkins-app
    ports:
      - "8084:8080"
      - "50000:50000"
    environment:
      - JENKINS_OPTS=--prefix=/jenkins
    volumes:
      - "/jenkins/data:/var/jenkins_home"
#    deploy:
#      resources:
#        limits: 
#          cpus: '2'
#          memory: 2g
#        reservations:
#          cpus: '1'
#          memory: 1512m