services:
  jenkins:
    image: delinel/devops:myjenkins-1.0.0
    restart: always
    container_name: jenkins-app
    ports:
      - "8084:8080"
      - "50000:50000"
    environment:
      - JENKINS_OPTS=--prefix=/   # ==> http://ip:port/
    # Sous reseau reservé aux applis: 10.0.1.0/24
    networks:
      ionos_network_appli:
        #ipv4_address: 10.0.1.10
    volumes:
      - "/jenkins/data:/var/jenkins_home"
#    deploy:
#      resources:
#        limits: 
#          cpus: '2'
#          memory: 2g
#        reservations:
#          cpus: '1'
#          memory: 1512m

networks:
  ionos_network_appli:
    name: ionos_net_appli
    driver: bridge
    ipam:
      config:
      - subnet: 10.0.1.0/24
        gateway: 10.0.1.1    