services:
  nexus_app:
    image: sonatype/nexus3:3.71.0-java17-alpine
    restart: always
    container_name: nexus-app
#    deploy:
#      resources:
#        limits: 
#          cpus: '2'
#          memory: 2g
#        reservations:
#          cpus: '1'
#          memory: 1512m
    ports:
      - "8081:8081"
    networks:
      ionos_network_appli:
        #ipv4_address: 10.0.1.10
    volumes:
      - "/nexus/data:/nexus-data"

networks:
  ionos_network_appli:
    name: ionos_net_appli
    driver: bridge
    ipam:
      config:
      - subnet: 10.0.1.0/24
        gateway: 10.0.1.1