version: "3.8"
services:
  nginx-frontend:
    image: delinel/devops:nginx-frt-1.0.0
    restart: always
    container_name: nginx-frt
    ports:
      - "80:80"
      - "443:443"
    deploy:
      resources:
        limits:         # ressources reservées par appli
          cpus: '0.1'
          memory: 500M
        reservations:   # ressources limites à utiliser par l'appli
          cpus: '0.01'
          memory: 300M
    networks:
      ionos_network_frt:
#        ipv4_address: 192.168.100.9
      ionos_network_appli:
#        ipv4_address: 10.0.1.9
    volumes:
      - /docker/volumes/nginx-frt/conf.d:/etc/nginx/conf.d #copie le contenu phy vers le conteneur
      - logs:/var/log/nginx # copie des logs du conteneur vers la machine physique

# Sous reseau reservé aux applis: 10.0.1.0/24
networks:
  ionos_network_appli:
    name: ionos_net_appli
    driver: bridge
    ipam:
      config:
      - subnet: 10.0.1.0/24
        gateway: 10.0.1.1
# Sous reseau reservé aux frontaux: 192.168.100.0/24
  ionos_network_frt:
    name: ionos_net_frt
    driver: bridge
    ipam:
      config:
      - subnet: 192.168.100.0/24
        gateway: 192.168.100.1

volumes:
  logs:
    driver: local
    driver_opts:
      type: none
      device: /docker/volumes/nginx-frt/logs
      o: bind